#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:5.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /src
COPY ["Mono2Micro.MicroService.App.Operations.Web/Mono2Micro.MicroService.App.Operations.Web.csproj", "Mono2Micro.MicroService.App.Operations.Web/"]
RUN dotnet restore "Mono2Micro.MicroService.App.Operations.Web/Mono2Micro.MicroService.App.Operations.Web.csproj"
COPY . .
WORKDIR "/src/Mono2Micro.MicroService.App.Operations.Web"
RUN dotnet build "Mono2Micro.MicroService.App.Operations.Web.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Mono2Micro.MicroService.App.Operations.Web.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Mono2Micro.MicroService.App.Operations.Web.dll"]